# Generated by Django 3.0 on 2020-02-01 16:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_park_django', '0003_like_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=191)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixel_park_django.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixel_park_django.User')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
