# Generated by Django 3.0 on 2020-01-31 10:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=240)),
                ('password', models.CharField(max_length=191)),
                ('social_link', models.TextField(default='null')),
                ('is_admin', models.IntegerField(default=0)),
                ('image', models.ImageField(default='user.png', upload_to='')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixel_park_django.User')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('photo', models.ImageField(default='image.img', upload_to='')),
                ('status', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixel_park_django.Post')),
            ],
            options={
                'db_table': 'photos',
            },
        ),
    ]
