# Generated by Django 3.0 on 2020-02-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_park_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixel_park_django.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixel_park_django.User')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
    ]
